apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- keycloak-admin-credentials.yaml
- keycloak-database-credentials.yaml
- namespace.yaml
# - role.yaml
# - rolebinding.yaml
# - repository.yaml
# - terraform.yaml