apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base

# incubator
# - ../../../00_base/incubator/helloworld/
- ../../../00_base/incubator/test-nginx/

# stable
# - ../../../00_base/stable/nextcloud/

# patches:
#   - path: ./patches/example/example.yaml
